In [1]:
from shared.preface import *
import shared.functions as fct

### 2D grid, center coord. pairs.

In [9]:
# 2D spatial grid, discretized.
x, y = np.mgrid[-1:1.1:1., -1:1.1:1.]
# print(x, x.shape)
# print(y, y.shape)

# [x y] edge coordinate pairs of above grid.
xy = np.mgrid[-1:1.1:1., -1:1.1:1.].reshape(2,-1).T
# print(xy.shape)

x_centers = (x[1:,:] + x[:-1,:])/2.
# print(x_centers, x_centers.shape)
# print(x_centers[:,:-1], x_centers.shape)

y_centers = (y[:,1:] + y[:,:-1])/2.
# print(y_centers, y_centers.shape)
# print(y_centers[:-1,:], y_centers.shape)

# Create center coord.-pairs.
centers = np.array([x_centers[:,:-1], y_centers[:-1,:]])
# print(centers, centers.shape)

cent_coordPairs = centers.reshape(2,-1).T
print(cent_coordPairs, cent_coordPairs.shape)

[[-0.5 -0.5]
 [-0.5  0.5]
 [ 0.5 -0.5]
 [ 0.5  0.5]] (4, 2)


### 3D grid, center coord. pairs.

In [8]:
# 3D spatial grid, discretized.
x, y, z = np.mgrid[-1:1.1:1., -1:1.1:1., -1:1.1:1.]
# print(x[0,...], x.shape)

x_centers = (x[1:,...] + x[:-1,...])/2.
# print(x_centers, x_centers.shape)

y_centers = (y[:,1:,:] + y[:,:-1,:])/2.
# print(y_centers, y_centers.shape)

z_centers = (z[...,1:] + z[...,:-1])/2.
# print(z_centers, z_centers.shape)


# Create center coord.-pairs., truncate redundant points.
centers3D = np.array([
    x_centers[:,:-1,:-1], 
    y_centers[:-1,:,:-1], 
    z_centers[:-1,:-1,:]
])
# print(centers3D, centers3D.shape)

cent_coordPairs3D = centers3D.reshape(3,-1).T 
print(cent_coordPairs3D, cent_coordPairs3D.shape)

[[-0.5 -0.5 -0.5]
 [-0.5 -0.5  0.5]
 [-0.5  0.5 -0.5]
 [-0.5  0.5  0.5]
 [ 0.5 -0.5 -0.5]
 [ 0.5 -0.5  0.5]
 [ 0.5  0.5 -0.5]
 [ 0.5  0.5  0.5]] (8, 3)
