In [1]:
from shared.preface import *
import shared.functions as fct

In [82]:
# 2D spatial grid, discretized.
x, y = np.mgrid[-1:1.1:1., -1:1.1:1.]
# print(x, x.shape)
# print(y, y.shape)

x_centers = (x[1:,:] + x[:-1,:])/2.
# print(x_centers, x_centers.shape)
print(x_centers[:,:-1], x_centers.shape)

y_centers = (y[:,1:] + y[:,:-1])/2.
# print(y_centers, y_centers.shape)
print(y_centers[:-1,:], y_centers.shape)

# Create center coord.-pairs.
# centers = np.vstack((x_centers[:,:-1], y_centers[:-1,:]))
centers = np.array([x_centers[:,:-1], y_centers[:-1,:]])
print(centers, centers.shape)
cent_coordPairs = centers.reshape(2,-1).T #! now this we need for 3D...
print(cent_coordPairs, cent_coordPairs.shape)

# [x y] coordinate pairs of above grid.
xy = np.mgrid[-1:1.1:1., -1:1.1:1.].reshape(2,-1).T
# print(xy.shape)

[[-0.5 -0.5]
 [ 0.5  0.5]] (2, 3)
[[-0.5  0.5]
 [-0.5  0.5]] (3, 2)
[[[-0.5 -0.5]
  [ 0.5  0.5]]

 [[-0.5  0.5]
  [-0.5  0.5]]] (2, 2, 2)
[[-0.5 -0.5]
 [-0.5  0.5]
 [ 0.5 -0.5]
 [ 0.5  0.5]] (4, 2)


In [62]:
xy = np.mgrid[-1:1.1:1., -1:1.1:1.]
print(xy.shape)

xy1 = (xy[0,1:,:] + xy[0,:-1,:])/2.
print(xy1, xy1.shape)

xy2 = (xy1[1,1:] + xy1[1,:-1])/2.
print(xy2, xy2.shape)


(2, 3, 3)
[[-0.5 -0.5 -0.5]
 [ 0.5  0.5  0.5]] (2, 3)
[0.5 0.5] (2,)


In [55]:
# 3D spatial grid, discretized.
x, y, z = np.mgrid[-1:1.1:1., -1:1.1:1., -1:1.1:1.]
print(x[0,...], x.shape)

x_centers = (x[1:,...] + x[:-1,...])/2.
print(x_centers, x_centers.shape)

y_centers = (y[:,1:,:] + y[:,:-1,:])/2.
print(y_centers, y_centers.shape)

z_centers = (z[...,1:] + z[...,:-1])/2.
print(z_centers, z_centers.shape)

[[-1. -1. -1.]
 [-1. -1. -1.]
 [-1. -1. -1.]] (3, 3, 3)
[[[-0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5]
  [-0.5 -0.5 -0.5]]

 [[ 0.5  0.5  0.5]
  [ 0.5  0.5  0.5]
  [ 0.5  0.5  0.5]]] (2, 3, 3)
[[[-0.5 -0.5 -0.5]
  [ 0.5  0.5  0.5]]

 [[-0.5 -0.5 -0.5]
  [ 0.5  0.5  0.5]]

 [[-0.5 -0.5 -0.5]
  [ 0.5  0.5  0.5]]] (3, 2, 3)
[[[-0.5  0.5]
  [-0.5  0.5]
  [-0.5  0.5]]

 [[-0.5  0.5]
  [-0.5  0.5]
  [-0.5  0.5]]

 [[-0.5  0.5]
  [-0.5  0.5]
  [-0.5  0.5]]] (3, 3, 2)


In [47]:
xyz = np.mgrid[-1:1.1:1., -1:1.1:1., -1:1.1:1.]
print('3D original grid', xyz.shape)

# [x y z] coordinate pairs of above grid.
xys_coord_pairs = xyz.reshape(3,-1).T
print('3D coord. pairs', xys_coord_pairs.shape)

xyz_centers = (xyz[:,1:,...] + xyz[:,:-1,...])/2.
print('3D centers grid', xyz_centers.shape)

xyz_center_coordPairs = xyz_centers.reshape(3,-1).T
print('3D center coord. pairs', xyz_center_coordPairs.shape)

3D original grid (3, 3, 3, 3)
3D coord. pairs (27, 3)
3D centers grid (3, 2, 3, 3)
3D center coord. pairs (18, 3)


### Grid around MW center.