In [6]:
from shared.preface import *

# arr = jnp.load(f'L025N752/DMONLY/SigmaConstant00/no_gravity/initial_velocities.npy')
# arr.shape



[[0 1 2]
 [3 4 5]]
[3 4 5]


In [ ]:
from shared.preface import *


# Python code to extract unique first two string bits, with exclusions.

# Initialize empty set to hold unique filename prefixes
unique_prefixes = set()

# Directory path (This is a placeholder; replace with the actual directory path)
dir_path = 'L025N752/DMONLY/SigmaConstant00/data_precalculations'

# Loop through each file in the directory
for filename in os.listdir(dir_path):
    # Exclude filenames starting with 'nu_' or 'cell'
    if not filename.startswith(('nu_', 'cell', 'batch')):
        # Split the filename at underscores and take the first two elements
        prefix = '_'.join(filename.split('_')[:2])
        # Add the prefix to the set
        unique_prefixes.add(prefix)

# Output the set of unique prefixes
print(unique_prefixes)

In [ ]:
# Initialize empty list to hold matching filenames
matching_filenames = []

# Directory path (This is a placeholder; replace with the actual directory path)
dir_path = 'L025N752/DMONLY/SigmaConstant00/data_precalculations'

# Loop through each file in the directory
for filename in os.listdir(dir_path):
    # Check for filenames starting with 'DM_pos' and containing 'snap'
    if filename.startswith('DM_pos') and 'snap' and 'origID34' in filename and 'indices' not in filename:
        # Add the filename to the list
        matching_filenames.append(filename)

# Output the list of matching filenames
print(matching_filenames)

In [ ]:
from shared.preface import *
from sklearn.neighbors import KernelDensity


def compute_KDE(
    halo_id, snap, bandwidth=1.0, downsample_frac=1.0, 
    data_path="L025N752/DMONLY/SigmaConstant00/data_precalculations"):

    # Construct filename
    fname = f"{data_path}/DM_pos_origID{halo_id}_snap_00{snap}.npy"
    
    # Load data
    if not os.path.exists(fname):
        print(f"File {fname} does not exist.")
        return
    data = np.load(fname)
    
    # Check shape
    if data.shape[1] != 3:
        print("Data shape mismatch. Expected shape (N, 3).")
        return
    
    # Downsample data
    if downsample_frac < 1.0:
        n_samples = int(data.shape[0] * downsample_frac)
        np.random.seed(0)
        idx = np.random.choice(data.shape[0], n_samples, replace=False)
        data_downsampled = data[idx]
    else:
        data_downsampled = data
    
    # Compute KDE
    kde = KernelDensity(kernel='gaussian', bandwidth=bandwidth)
    kde.fit(data_downsampled)
    log_dens = kde.score_samples(data)
    densities = np.exp(log_dens)

    return densities


'''
KDE12 = compute_KDE(35, 12, bandwidth=5, downsample_frac=0.005)
KDE22 = compute_KDE(35, 22, bandwidth=5, downsample_frac=0.005)
KDE36 = compute_KDE(35, 36, bandwidth=5, downsample_frac=0.005)

np.save(f'KDE12_haloID35.npy', KDE12)
np.save(f'KDE22_haloID35.npy', KDE22)
np.save(f'KDE36_haloID35.npy', KDE36)
'''


KDE12 = compute_KDE(31, 12, bandwidth=5, downsample_frac=0.005)
KDE22 = compute_KDE(31, 22, bandwidth=5, downsample_frac=0.005)
KDE36 = compute_KDE(31, 36, bandwidth=5, downsample_frac=0.005)

np.save(f'KDE12_haloID31.npy', KDE12)
np.save(f'KDE22_haloID31.npy', KDE22)
np.save(f'KDE36_haloID31.npy', KDE36)

In [ ]:
from shared.preface import *
import matplotlib.colors as mcolors
import mplcyberpunk

def cmap_cyan_to_purple():
    cdict = {
        'red': [(0.0, 0.0, 0.0),  # cyan at 0
                (1.0, 0.5, 0.5)],  # dark purple at 1

        'green': [(0.0, 1.0, 1.0),  # cyan at 0
                  (1.0, 0.0, 0.0)],  # dark purple at 1

        'blue': [(0.0, 1.0, 1.0),  # cyan at 0
                 (1.0, 1.0, 1.0)]  # dark purple at 1
    }

    custom_cmap = mcolors.LinearSegmentedColormap(
        'custom_cmap_cyan_to_purple', 
        cdict
    )
    return custom_cmap


def cmap_light_to_dark_purple():
    cdict = {
        'red': [(0.0, 0.5, 0.5),  # light purple at 0
                (1.0, 0.2, 0.2)],  # dark purple at 1

        'green': [(0.0, 0.4, 0.4),  # light purple at 0
                  (1.0, 0.0, 0.0)],  # dark purple at 1

        'blue': [(0.0, 0.9, 0.9),  # light purple at 0
                 (1.0, 0.5, 0.5)]  # dark purple at 1
    }

    custom_cmap = mcolors.LinearSegmentedColormap(
        'custom_cmap_light_to_dark_purple', 
        cdict
    )
    return custom_cmap


def cmap_maroon_to_dark_purple():
    cdict = {
        'red': [(0.0, 0.5, 0.5),  # maroon at 0
                (1.0, 0.2, 0.2)],  # dark purple at 1

        'green': [(0.0, 0.0, 0.0),  # maroon at 0
                  (1.0, 0.0, 0.0)],  # dark purple at 1

        'blue': [(0.0, 0.2, 0.2),  # maroon at 0
                 (1.0, 0.5, 0.5)]  # dark purple at 1
    }

    custom_cmap = mcolors.LinearSegmentedColormap('custom_cmap_maroon_to_dark_purple', cdict)
    return custom_cmap


def cmap_dark_maroon_to_dark_purple():
    cdict = {
        'red': [(0.0, 0.35, 0.35),  # starting color at 0 (about a third in)
                (1.0, 0.2, 0.2)],  # dark purple at 1

        'green': [(0.0, 0.0, 0.0),  # starting color at 0 (about a third in)
                  (1.0, 0.0, 0.0)],  # dark purple at 1

        'blue': [(0.0, 0.1, 0.1),  # starting color at 0 (about a third in)
                 (1.0, 0.5, 0.5)]  # dark purple at 1
    }

    custom_cmap = mcolors.LinearSegmentedColormap('custom_cmap_maroon_to_dark_purple', cdict)
    return custom_cmap


# plt.style.use("cyberpunk")


def plot_KDE_halo(
    halo_id, snap, densities, downsample_frac,
    data_path="L025N752/DMONLY/SigmaConstant00/data_precalculations"):

    # Construct filename
    fname = f"{data_path}/DM_pos_origID{halo_id}_snap_00{snap}.npy"
    data = np.load(fname)
    
    # Downsample data
    if downsample_frac < 1.0:
        n_samples = int(data.shape[0] * downsample_frac)
        np.random.seed(0)
        idx = np.random.choice(data.shape[0], n_samples, replace=False)
        data_downsampled = data[idx]
    else:
        data_downsampled = data    

    # Sort data and densities for plotting
    sort_idx = np.argsort(densities)
    sorted_data = data[sort_idx]
    sorted_densities = densities[sort_idx]
    sorted_densities /= np.max(sorted_densities)

    # Create 3D plot
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')    
    cmap = cmap_light_to_dark_purple()

    # Scatter plot with color mapping
    sc = ax.scatter(sorted_data[:, 0], sorted_data[:, 1], sorted_data[:, 2], 
                    c=sorted_densities[::-1], cmap=cmap, s=5, alpha=0.2, 
                    edgecolors='none', 
                    zorder=sorted_densities
                    )
    
    # Turn off axis labels, ticks, and grid
    ax.set_axis_off()
    
    mplcyberpunk.add_glow_effects()

    # Show plot
    plt.show()


hID = 31
# hID = 35
snaps = [12,22,36]
for si in snaps:
    plot_KDE_halo(
        halo_id=hID, snap=si, downsample_frac=0.005, 
        densities=np.load(f'KDE{si}_haloID{hID}.npy')
    )